# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "bulletin_board_access_conditions", :force => true do |t|
    t.column "bulletin_board_id", :integer,                 :null => false
    t.column "conditions",        :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "lock_version",      :integer,  :default => 0
  end

  create_table "bulletin_board_attachments", :force => true do |t|
    t.column "bulletin_board_id", :integer,                     :null => false
    t.column "name",              :string
    t.column "download_name",     :string
    t.column "host",              :string
    t.column "path",              :string
    t.column "file_name",         :string
    t.column "passed_quarantine", :boolean,  :default => false
    t.column "out_of_quarantine", :boolean,  :default => false
    t.column "quarantine_status", :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "lock_version",      :integer,  :default => 0
  end

  create_table "bulletin_boards", :force => true do |t|
    t.column "title",        :string,   :default => "",   :null => false
    t.column "comment",      :string
    t.column "sort_order",   :integer,  :default => 0
    t.column "opened_at",    :date
    t.column "closed_at",    :date
    t.column "enable",       :boolean,  :default => true
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "lock_version", :integer,  :default => 0
  end

  add_index "bulletin_boards", ["sort_order"], :name => "bb_sort"

  create_table "calendars", :force => true do |t|
    t.column "date",           :date,                    :null => false
    t.column "unit",           :integer,                 :null => false
    t.column "start_at",       :time
    t.column "end_at",         :time
    t.column "term",           :integer
    t.column "reservation_id", :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "room_id",        :integer,                 :null => false
    t.column "lock_version",   :integer,  :default => 0
  end

  add_index "calendars", ["room_id", "date", "unit"], :name => "room_date_unit", :unique => true
  add_index "calendars", ["date", "unit"], :name => "index_calendars_on_date_and_unit"

  create_table "privileges", :force => true do |t|
    t.column "name",         :string,   :default => "", :null => false
    t.column "sort_order",   :integer,  :default => 0,  :null => false
    t.column "controller",   :string
    t.column "action",       :string
    t.column "node_type",    :string
    t.column "parent_id",    :integer
    t.column "lock_version", :integer,  :default => 0
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "privileges_roles", :id => false, :force => true do |t|
    t.column "privilege_id", :integer, :null => false
    t.column "role_id",      :integer, :null => false
  end

  add_index "privileges_roles", ["privilege_id", "role_id"], :name => "pk_privileges_roles", :unique => true

  create_table "reservations", :force => true do |t|
    t.column "name",            :string
    t.column "description",     :string
    t.column "user_id",         :integer,                     :null => false
    t.column "room_id",         :integer
    t.column "date",            :date,                        :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "lock_version",    :integer,  :default => 0
    t.column "use_tel_meeting", :boolean,  :default => false, :null => false
    t.column "have_a_visitor",  :boolean,  :default => false, :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "name",         :string,   :default => "", :null => false
    t.column "lock_version", :integer,  :default => 0
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "rooms", :force => true do |t|
    t.column "name",     :string
    t.column "capacity", :integer, :default => 0
    t.column "tel",      :string
  end

  create_table "users", :force => true do |t|
    t.column "login_id",            :string,   :default => "",           :null => false
    t.column "name",                :string,   :default => "",           :null => false
    t.column "admin",               :boolean,  :default => false
    t.column "enable",              :boolean,  :default => true
    t.column "password_hash",       :string
    t.column "password_salt",       :string
    t.column "password_term_valid", :date,     :default => '2008-05-25'
    t.column "password_issued",     :boolean,  :default => false
    t.column "last_login_at",       :datetime
    t.column "password_faults",     :integer,  :default => 0
    t.column "lock_version",        :integer,  :default => 0
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "role_id",             :integer
  end

  add_index "users", ["login_id"], :name => "uniq_login_id", :unique => true

end
